DROP TABLE IF EXISTS plays;
DROP TABLE IF EXISTS consists_of;

DROP TABLE IF EXISTS WorldCups;
DROP TABLE IF EXISTS Goals;
DROP TABLE IF EXISTS Matches;
DROP TABLE IF EXISTS Rounds;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS Players;
DROP TABLE IF EXISTS Teams;
